kind: pipeline
type: docker
name: dewar

steps:
- name: testbuild
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - echo "ENVIRONMENT!"
  - export
  - echo "DONE ENVIRONMENT"
  - pipenv run pytest
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    S3_ENDPOINT_URL:
      from_secret: S3_ENDPOINT_URL
