kind: pipeline
type: docker
name: dewar

trigger:
  event:
    exclude: [ promote ]
steps:
- name: pytest
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pytest --cov=dewar
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    S3_ENDPOINT_URL:
      from_secret: S3_ENDPOINT_URL
- name: pylint
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pylint dewar
- name: sonarqube
  image: newtmitch/sonar-scanner
  secrets:
    - source: SONAR_TOKEN
      target: SONAR_TOKEN
    - source: SONAR_HOST
      target: SONAR_HOST
  commands:
    - sonar-scanner -Dsonar.projectKey=dewar -Dsonar.sources=. -Dsonar.host.url=https://$SONAR_HOST -Dsonar.login=$SONARTOKEN
