kind: pipeline
type: docker
name: dewar

trigger:
  event:
    exclude: [ promote ]
steps:
- name: pytest
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pytest --cov=dewar
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
    S3_ENDPOINT_URL:
      from_secret: S3_ENDPOINT_URL
- name: pylint
  image: python:3.7
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pylint --disable=C0301,W0511 dewar
  # C0301 - line too long
  # W0511 - TODO's
